fix: Correct scope issue in investor create/delete functions
Fixed TypeError: this.createInvestorViaAPI is not a function
- Changed this.createInvestorViaAPI to directUserServices.createInvestorViaAPI
- Changed this.deleteInvestorViaAPI to directUserServices.deleteInvestorViaAPI
- Functions were at different scope levels causing reference error

Resolves issue when creating or deleting investors in DonorManagement.